# Generated by Django 5.1.5 on 2025-01-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='postFore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postTags', to='posts.post'),
        ),
    ]
