# Generated by Django 5.1.5 on 2025-01-27 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_contact_options_contact_is_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_admin', models.CharField(max_length=50, verbose_name='ادمین پاسخ دهنده')),
                ('response', models.TextField(verbose_name='متن جواب')),
                ('answer_time', models.DateTimeField(verbose_name='زمان پاسخ')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conracts', to='posts.contact', verbose_name='سوالات')),
            ],
            options={
                'verbose_name': 'جواب',
                'verbose_name_plural': 'جواب ها',
            },
        ),
    ]
