# Generated by Django 5.1.5 on 2025-01-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان پاسخ'),
        ),
    ]
