# Generated by Django 5.1.5 on 2025-01-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_answer_answer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
