# Generated by Django 5.1.5 on 2025-01-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(default='تگ اول', to='posts.tag', verbose_name='تگ ها'),
        ),
    ]
